version: "3.8"

services: 
  database: 
    image: postgres
    container_name: hublocal_database
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hublocal
      - POSTGRES_DB=HublocalDB
    restart: always
    volumes: 
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: hublocal_back
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
    restart: always
    links: 
      - database
    depends_on:
      - database


volumes: 
  pgdata: 
    driver: local
