version: "3.8"

services: 
  database: 
    image: postgres:latest
    container_name: hublocal_database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=hublocal_db
      - POSTGRES_USER=hublocal
      - POSTGRES_PASSWORD=hublocal123
    volumes:
      - pgdata:/var/lib/postgresql/data


  app: 
    build: .
    container_name: hublocal_back
    restart: always
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database


volumes: 
  pgdata: 
    driver: local
